// <auto-generated />
using System;
using Bil372Project.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bil372Project.DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251201002425_SeedInit")]
    partial class SeedInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Bil372Project.EntityLayer.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Bil372Project.EntityLayer.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NewValues")
                        .HasColumnType("longtext");

                    b.Property<string>("OldValues")
                        .HasColumnType("longtext");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Bil372Project.EntityLayer.Entities.MeasurementForMl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Bmi")
                        .HasColumnType("double");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("DailyCalorieTarget")
                        .HasColumnType("double");

                    b.Property<double>("FatGrams")
                        .HasColumnType("double");

                    b.Property<double>("ProteinGrams")
                        .HasColumnType("double");

                    b.Property<double>("SodiumMg")
                        .HasColumnType("double");

                    b.Property<double>("SugarGrams")
                        .HasColumnType("double");

                    b.Property<int>("UserMeasureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserMeasureId")
                        .IsUnique();

                    b.ToTable("MeasurementsForMl", (string)null);
                });

            modelBuilder.Entity("Bil372Project.EntityLayer.Entities.UserDietPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Breakfast")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Dinner")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Lunch")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Snack")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("UserMeasureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserMeasureId");

                    b.ToTable("UserDietPlans", (string)null);
                });

            modelBuilder.Entity("Bil372Project.EntityLayer.Entities.UserGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("DailyWaterTarget")
                        .HasColumnType("int");

                    b.Property<int?>("GoalDurationWeeks")
                        .HasColumnType("int");

                    b.Property<string>("MotivationNote")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<double?>("TargetWeightKg")
                        .HasColumnType("double");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WaterConsumedToday")
                        .HasColumnType("int");

                    b.Property<int?>("WeeklyActivityTarget")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserGoals", (string)null);
                });

            modelBuilder.Entity("Bil372Project.EntityLayer.Entities.UserMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("DietaryPreference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Diseases")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<double>("HeightCm")
                        .HasColumnType("double");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserMeasures", (string)null);
                });

            modelBuilder.Entity("Bil372Project.EntityLayer.Entities.AuditLog", b =>
                {
                    b.HasOne("Bil372Project.EntityLayer.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bil372Project.EntityLayer.Entities.MeasurementForMl", b =>
                {
                    b.HasOne("Bil372Project.EntityLayer.Entities.UserMeasure", "UserMeasure")
                        .WithOne("MeasurementForMl")
                        .HasForeignKey("Bil372Project.EntityLayer.Entities.MeasurementForMl", "UserMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserMeasure");
                });

            modelBuilder.Entity("Bil372Project.EntityLayer.Entities.UserDietPlan", b =>
                {
                    b.HasOne("Bil372Project.EntityLayer.Entities.UserMeasure", "UserMeasure")
                        .WithMany("DietPlans")
                        .HasForeignKey("UserMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserMeasure");
                });

            modelBuilder.Entity("Bil372Project.EntityLayer.Entities.UserGoal", b =>
                {
                    b.HasOne("Bil372Project.EntityLayer.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bil372Project.EntityLayer.Entities.UserMeasure", b =>
                {
                    b.HasOne("Bil372Project.EntityLayer.Entities.AppUser", "User")
                        .WithMany("UserMeasures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bil372Project.EntityLayer.Entities.AppUser", b =>
                {
                    b.Navigation("UserMeasures");
                });

            modelBuilder.Entity("Bil372Project.EntityLayer.Entities.UserMeasure", b =>
                {
                    b.Navigation("DietPlans");

                    b.Navigation("MeasurementForMl")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
